# yaml-language-server: $schema=https://render.com/schemas/blueprint.json
# Define Render services
services:
  - type: web
    name: blogpost_db
    runtime: docker
    plan: free
    rootDir: backend
    buildCommand: |
      cp .env.render .env
      chmod +x deploy-entrypoint.sh
    startCommand: ./deploy-entrypoint.sh
    envVars:
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-0-us-west-1.pooler.supabase.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.oawesktltrtfudeipgrs
      - key: DB_PASSWORD
        value: Adelani8991#
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: SANCTUM_STATEFUL_DOMAINS
        value: blog-post-aorf.onrender.com,blogpost-db.onrender.com,.onrender.com
      - key: SESSION_DOMAIN
        value: .onrender.com