# yaml-language-server: $schema=https://render.com/schemas/blueprint.json
# Define Render services
services:
  # Backend API service
  - type: web
    name: blogpost-api
    runtime: docker
    plan: free
    rootDir: backend
    buildCommand: |
      cp .env.render .env
      chmod +x deploy-entrypoint.sh
    startCommand: ./deploy-entrypoint.sh
    envVars:
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-0-us-west-1.pooler.supabase.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      # These should be set in the Render dashboard as environment variables for security
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://blogpost-api.onrender.com
      - key: SANCTUM_STATEFUL_DOMAINS
        value: blog-post-aorf.onrender.com,blogpost-api.onrender.com,.onrender.com
      - key: SESSION_DOMAIN
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS 
        value: https://blog-post-aorf.onrender.com,https://blogpost-api.onrender.com

  # Frontend service
  - type: web
    name: blog-post-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://blogpost-api.onrender.com