# yaml-language-server: $schema=https://render.com/schemas/blueprint.json
# Define Render services
services:
  - type: web
    name: blogpost_db
    runtime: docker
    plan: free
    rootDir: backend
    buildCommand: |
      cp .env.render .env
      composer install --no-dev --optimize-autoloader
      php artisan key:generate --force
    startCommand: |
      php artisan config:clear
      php artisan migrate --force
      php artisan storage:link
      php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-0-us-west-1.pooler.supabase.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.oawesktltrtfudeipgrs
      - key: DB_PASSWORD
        value: Adelani8991#
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true