# yaml-language-server: $schema=https://render.com/schemas/blueprint.json
# Define Render services
services:
  - type: web
    name: Blog_db
    runtime: docker
    plan: free
    rootDir: main
    envVars:
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true